### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/Battle-Chat#11]
[Travis CI](http://about.travis-ci.org/docs/) should be setup for [the project](https://travis-ci.org/ninetwozero/Battle-Chat/), and effectively grabbing the [ActionBarSherlock library](http://www.actionbarsherlock.com) for this as well.

**Comment by peter-budo** [comment]
Why are you referencing seemingly unrelated task/issues with this? Stuff as this Pull https://github.com/ninetwozero/Battle-Chat/pull/20 should be here

**Comment by karllindmark** [comment]
Should be easier to achieve now with #29 in place.

**Comment by peter-budo** [comment]
If you can provide me with access to it I can have look at it
