### ISSUE TITLE
Optimize for tablets

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/Battle-Chat#21]
The app needs tablet support. Prerequisites would be as follows:
- Fragmentized activities
- Investigation regarding a good way to do so

**Comment by karllindmark** [comment]
#22 fixes the login.

**Comment by peter-budo** [comment]
Why not produce some sketches and discuss them with people?

**Comment by karllindmark** [comment]
A quick sketch, obviously looking a lot nicer in-app. :+1: 
<img src="http://i.imgur.com/8p6d7ge.png" />

This is the most common layout, also called Master Detail Flow.

@peter-budo @redfungi

**Comment by peter-budo** [comment]
Yes for tablet or phone on landscape

**Comment by karllindmark** [comment]
Actual rough implementation right now:
<img src="http://i.imgur.com/iwTgAWP.png" alt="" />

**Comment by karllindmark** [comment]
Should probably have a selection to the left, to indicate who we're chatting to. :-)

**Comment by karllindmark** [comment]
@peter-budo

**Comment by peter-budo** [comment]
Left section should be much smaller, let say 33% and rest should be taken by actual chat. Person whom yuo are talking too should be highlighted

**Comment by karllindmark** [comment]
On ice as I'm not really a designer, ha.

**Comment by karllindmark** [comment]
Addressed by slidingmenu-impl branch.
