### ISSUE TITLE
Provide intent to enable other apps to invoke Battle-Chat and use it

### ISSUE THREAD

**Issue by peter-budo** [ninetwozero/Battle-Chat#45]
What I would like to see is be able to launch Battle-Chat from BF3-Droid through intent instead of having whole app as part of droid project.
These links should be helpful
[Allowing Other Apps to Start Your Activity](http://developer.android.com/training/basics/intents/filters.html)
[Sending the User to Another App](http://developer.android.com/training/basics/intents/sending.html)

We used something similar for showcasing Skitch in one of customer's apps

```
Intent sendIntent = new Intent("com.evernote.action.CREATE_NEW_NOTE");
sendIntent.putExtra(Intent.EXTRA_TITLE, "Web Clip");
sendIntent.putExtra(Intent.EXTRA_TEXT, fullContents);
sendIntent.setType("text/plain");
startActivity(sendIntent);
```

**Comment by karllindmark** [comment]
It's startable via the intent - we may add features in the future that, like, bring up the friends list and enable "quick sharing". :-)
