### ISSUE TITLE
Chat is triggering a sound if there are messages in a chat

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/Battle-Chat#51]
Chat is triggering a sound if there are messages in a chat, not necessarily new ones. It should only make a sound when a new message (or unread message) is available.

**Comment by peter-budo** [comment]
You would have to have first a way to discover if there is new unread message, as far I know at the moment JSON hold stack of messages with no delivery status

**Comment by karllindmark** [comment]
So true. There is some sort of "unreadCount" tied to the COM at large, but not per individual. :-) @peter-budo
