### ISSUE TITLE
Clicking on the "Logged in as"-box in Battle Chat should open BF4 Droid?

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/Battle-Chat#53]
Clicking on the "Logged in as"-box in Battle Chat should open BF4 Droid? Seems like a good idea if you ask me, but might not be.

**Comment by peter-budo** [comment]
Wrong both way dependency is not good. One way dependency meaning from Bf4 droid to battle-chat is correct

**Comment by karllindmark** [comment]
When you put it that way...

**Comment by peter-budo** [comment]
Simple logic, you want others to integrate your Battle-Chat in their apps not you to create dependency on their
