### ISSUE TITLE
An empty toast notification when opening the app

### ISSUE THREAD

**Issue by dpeukert** [ninetwozero/Battle-Chat#71]
![screenshot_2014-04-23-16-27-35](https://cloud.githubusercontent.com/assets/3451904/2778556/8174755a-caf3-11e3-9fbc-29a7cf1e0ad5.png)

**Comment by dpeukert** [comment]
Sorry for the size of the screenshot.

**Comment by karllindmark** [comment]
Thanks for the report - did the app work as expected apart from that toast?

**Comment by dpeukert** [comment]
I thought so, but when I tested sending messages, it says: You need to enter a message even if I enter something. The empty toast also shows up when I open a conversation.

**Comment by karllindmark** [comment]
That seems a bit broken. Did you try logging out and then in again? I'm
guessing it's some limbo state in between. Will need to address the session
expiration better. :-)

**Comment by dpeukert** [comment]
Relogging fixed both problems, thanks.
